const homeUrl = 'https://shopee.vn/';
const coinUrl = 'https://shopee.vn/shopee-coins';
const luckyUrl = 'https://shopee.vn/quatangshopee';
const cookies = [
    {
        "domain": ".shopee.vn",
        "expirationDate": 253402257600,
        "hostOnly": false,
        "httpOnly": false,
        "name": "G_ENABLED_IDPS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "google",
        "id": 1
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1599034698.392749,
        "hostOnly": false,
        "httpOnly": false,
        "name": "REC_MD_41_1000121",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1599034625_0_50_0_43",
        "id": 2
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2228152638.57798,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_CLIENTID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "5iWTZuYfb2E9lLrUujxejjhhggadqngu",
        "id": 3
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2229754563.074479,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_EC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "+dtQ8xm+6hC1OpZXHztQpfs9AIKXOIJTrQUvaVCEMUi8Xhlq/E6IKHQ44yD5ryOVLwuosJrVEInC7T22Acv4SKcPwj8JSe30I6ooqm31TsgwQgKusqKF9DftLPPOZkBDR7UooDy0UPo3RklkwiLelQghyMrLPpFNCLFcIBXtTo4=",
        "id": 4
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2226287415.361156,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_F",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "5iWTZuYfb2E9lLrUBfP18GoZ4cpFQOVG",
        "id": 5
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2229754650.54299,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_R_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"OkzZZS9fK1dTR+lgOBrZjo0bsXKiI7jqPfMzGMe9nw8jMIosMbEPCbqj8xEQpzG/8QK6+heQI8wSR87oP2kXWQLR3X9rJx6kzs7Dpa1Zi8E=\"",
        "id": 6
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2229754650.543165,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_R_T_IV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"pxVQFCdTgg00rjo9EhMcSA==\"",
        "id": 7
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1599121050.543263,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SPC_SI",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "y4mdja24wo8ncet1rj85rdtq4rrpmmmd",
        "id": 8
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2229754327.645564,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_U",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "69252628",
        "id": 9
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "csrftoken",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "KYUkxliIibHqgt5IxQv0gvAX2EuPamdk",
        "id": 10
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 2226287415.361199,
        "hostOnly": true,
        "httpOnly": true,
        "name": "REC_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "f5b3f252-cd6b-11ea-b661-f41d6bf861df",
        "id": 11
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_IA",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "1",
        "id": 12
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 2229754650.543217,
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"OkzZZS9fK1dTR+lgOBrZjo0bsXKiI7jqPfMzGMe9nw8jMIosMbEPCbqj8xEQpzG/8QK6+heQI8wSR87oP2kXWQLR3X9rJx6kzs7Dpa1Zi8E=\"",
        "id": 13
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 2229754650.543108,
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_T_IV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"pxVQFCdTgg00rjo9EhMcSA==\"",
        "id": 14
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "welcomePkgShown",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "true",
        "id": 15
    }
];

module.exports = {
    cookies,
    homeUrl,
    coinUrl,
    luckyUrl
}