const coinUrl = 'https://shopee.vn/shopee-coins';
const luckyUrl = 'https://shopee.vn/quatangshopee';
const cookies = [
    {
        "domain": ".shopee.vn",
        "expirationDate": 1611013517,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1.1.132660091.1603237518",
        "id": 1
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 253402257600,
        "hostOnly": false,
        "httpOnly": false,
        "name": "G_ENABLED_IDPS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "google",
        "id": 2
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1606454114.840671,
        "hostOnly": false,
        "httpOnly": false,
        "name": "REC_MD_41_1000121",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1606454114_0_50_0_49",
        "id": 3
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2230264165.861061,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_CLIENTID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "xMEtnHwdWz8bdCnaupqmddqmoxadfhfk",
        "id": 4
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2237173818.409571,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SPC_EC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "ghjAdlHM6b4WrxL21JSgWud4ZObseVOZ3KUz0xbohcpTAayNmzqIbBbWv52IBUJ53gegMQYQQPTBkpA8Fmgd7Ys+sBVD0AWpYqmC6ajLExL/CX1r1qFZEdnFITEcgenvWDekOsPjwnWVkBV95Hkb0ldHogxeMc0uCEhdvK5VoLk=",
        "id": 5
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2230264149.176499,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_F",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "xMEtnHwdWz8bdCnaPvSDIKUpkWVs9U1e",
        "id": 6
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2237173817.879836,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_R_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"qMDX07qEk/TB+AV8SaK3rxYorCXge13HUgAcD66Xn/n2nz7WTohcXailECc/oty78NdjZGK8oqUapXGIhieZhOvupoqcLRQ1ECkNdhQ/m2A=\"",
        "id": 7
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2237173817.88,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_R_T_IV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"fF0JnWCo1IhWOea859AfJw==\"",
        "id": 8
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1606540217.880093,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SPC_SI",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "bfftocvn.FSFI3wmxuKUb7OBB9yi79fjPtQH2xd7v",
        "id": 9
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2237173813.192274,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_U",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "166811145",
        "id": 10
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "csrftoken",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "hr4yVZ43TINxmPpDei1lmCsTOrrLDhUi",
        "id": 11
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 2230264149,
        "hostOnly": true,
        "httpOnly": true,
        "name": "REC_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "03d61f6e-f197-11ea-8772-f898ef6c83f7",
        "id": 12
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_IA",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "1",
        "id": 13
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 2237173817.88005,
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"qMDX07qEk/TB+AV8SaK3rxYorCXge13HUgAcD66Xn/n2nz7WTohcXailECc/oty78NdjZGK8oqUapXGIhieZhOvupoqcLRQ1ECkNdhQ/m2A=\"",
        "id": 14
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 2237173817.879946,
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_T_IV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"fF0JnWCo1IhWOea859AfJw==\"",
        "id": 15
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "welcomePkgShown",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "true",
        "id": 16
    }
];

module.exports = {
    cookies,
    coinUrl,
    luckyUrl
}