const coinUrl = 'https://shopee.vn/shopee-coins';
const luckyUrl = 'https://shopee.vn/quatangshopee';
const cookies = [
    {
        "domain": ".shopee.vn",
        "expirationDate": 1611013517,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1.1.132660091.1603237518",
        "id": 1
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 253402257600,
        "hostOnly": false,
        "httpOnly": false,
        "name": "G_ENABLED_IDPS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "google",
        "id": 2
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1603846656.947866,
        "hostOnly": false,
        "httpOnly": false,
        "name": "REC_MD_41_1000121",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1603846438_0_50_0_47",
        "id": 3
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2230264165.861061,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_CLIENTID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "xMEtnHwdWz8bdCnaupqmddqmoxadfhfk",
        "id": 4
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2234566358.155203,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_EC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "k0Mf7KtlVNXP3tlQ4pscIqPtdVWJRx/zK1y3mVjUtMfywJocH1KfD8UgQz/RHnwnBYzTYEVMVhbzrJUsPMefrd260LIl4ykaWnwQqeRF6YgD+9TQIkTcd6X12NQZs4PgGHf1eCgLe313mrcB7a+8Lw==",
        "id": 5
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2230264149.176499,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_F",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "xMEtnHwdWz8bdCnaPvSDIKUpkWVs9U1e",
        "id": 6
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2234566359.136479,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_R_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"wZ/IyLI601YbQEStYlqZ9J4EqAVHYry2H2r4OP4K+JZE8GnbtzPyr08d/fgCaIWK203ZJeWt/n69Bzx6X/AWAa5whh/x92Aa+mpAr/fcYTs=\"",
        "id": 7
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2234566359.136599,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_R_T_IV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"glzkKuvsnuwK+mJiCJf2qQ==\"",
        "id": 8
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1603932759.136675,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SPC_SI",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "mall.8L3mWxjmLyV4bEnIIMyI3QaNeE7ppGPL",
        "id": 9
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2234566135.459544,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_U",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "69252628",
        "id": 10
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "csrftoken",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "urM30ggdustdYKxd9L5MQmUKcZWrxFVg",
        "id": 11
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 2230264149,
        "hostOnly": true,
        "httpOnly": true,
        "name": "REC_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "03d61f6e-f197-11ea-8772-f898ef6c83f7",
        "id": 12
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_IA",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "1",
        "id": 13
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 2234566359.136639,
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"wZ/IyLI601YbQEStYlqZ9J4EqAVHYry2H2r4OP4K+JZE8GnbtzPyr08d/fgCaIWK203ZJeWt/n69Bzx6X/AWAa5whh/x92Aa+mpAr/fcYTs=\"",
        "id": 14
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 2234566359.136557,
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_T_IV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"glzkKuvsnuwK+mJiCJf2qQ==\"",
        "id": 15
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "welcomePkgShown",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "true",
        "id": 16
    }
];

module.exports = {
    cookies,
    coinUrl,
    luckyUrl
}