const homeUrl = 'https://shopee.vn/';
const coinUrl = 'https://shopee.vn/shopee-coins';
const luckyUrl = 'https://shopee.vn/quatangshopee';
const cookies = [
    {
        "domain": ".shopee.vn",
        "expirationDate": 253402257600,
        "hostOnly": false,
        "httpOnly": false,
        "name": "G_ENABLED_IDPS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "google",
        "id": 1
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1599787674.438798,
        "hostOnly": false,
        "httpOnly": false,
        "name": "REC_MD_41_1000121",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1599787674_0_50_0_43",
        "id": 2
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2230264165.861061,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_CLIENTID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "xMEtnHwdWz8bdCnaupqmddqmoxadfhfk",
        "id": 3
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2230507376.724475,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_EC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "SxKlvYvtmuQa3teuRYBYnJFBx4T+5izAN3vvzNfKI8nvWZQ9DWkpcSRvuN6+Xwyxwhev2dQGlbjOn9diBItI6JHT+RFQvRhVKuv2EB483Gt0vR0RF7h87tkiOjTDsfra/FNQQ2Ej6/uBuM7VwImDLeC4r1zOryxqP4lYe0DXljo=",
        "id": 4
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2230264149.176499,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_F",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "xMEtnHwdWz8bdCnaPvSDIKUpkWVs9U1e",
        "id": 5
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2230507548.468621,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_R_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"5GUlX4bl8RaAJlGXRZ5bvZqfXb3uk6Cvp676NZz+3jWkswaIgIrFEa3YWCzU9GJVNYMCvS1FzvXbtdN7XNG2KV0ppcGP3DQ1Iv4Lc+HD7TE=\"",
        "id": 6
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2230507548.468723,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_R_T_IV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"j2ZoMiF8Zl+dpMUyzCDz7Q==\"",
        "id": 7
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1599873948.468772,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SPC_SI",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "fwiip1hr1k9kog958nr63sagits725is",
        "id": 8
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2230264187.32467,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_U",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "69252628",
        "id": 9
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "csrftoken",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "eYDsRPFXn4InxkaLLqMoHtQsffVPp4Fa",
        "id": 10
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 2230264149.17652,
        "hostOnly": true,
        "httpOnly": true,
        "name": "REC_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "03d61f6e-f197-11ea-8772-f898ef6c83f7",
        "id": 11
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_IA",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "1",
        "id": 12
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 2230507548.468749,
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"5GUlX4bl8RaAJlGXRZ5bvZqfXb3uk6Cvp676NZz+3jWkswaIgIrFEa3YWCzU9GJVNYMCvS1FzvXbtdN7XNG2KV0ppcGP3DQ1Iv4Lc+HD7TE=\"",
        "id": 13
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 2230507548.468685,
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_T_IV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"j2ZoMiF8Zl+dpMUyzCDz7Q==\"",
        "id": 14
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "welcomePkgShown",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "true",
        "id": 15
    }
];

module.exports = {
    cookies,
    homeUrl,
    coinUrl,
    luckyUrl
}