const coinUrl = 'https://shopee.vn/shopee-coins';
const luckyUrl = 'https://shopee.vn/quatangshopee';
const cookies = [
    {
        "domain": ".shopee.vn",
        "expirationDate": 253402257600,
        "hostOnly": false,
        "httpOnly": false,
        "name": "G_ENABLED_IDPS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "google",
        "id": 1
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1602598056.80022,
        "hostOnly": false,
        "httpOnly": false,
        "name": "REC_MD_22_1000944",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1602597935_0_10_0_10",
        "id": 2
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1602598056.612744,
        "hostOnly": false,
        "httpOnly": false,
        "name": "REC_MD_41_1000121",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1602598055_0_50_0_43",
        "id": 3
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2230264165.861061,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_CLIENTID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "xMEtnHwdWz8bdCnaupqmddqmoxadfhfk",
        "id": 4
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2233317758.417747,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_EC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "MeYzZ2CuNbKlpDSXTrBywQ5yiwG6QudSntIbzh34WXOC+FkW0WL/yFbY/oYhzRBrBWeQ2xC5eZqNNiz0eea1EXUAcfM9IZ2OZ/g/esdM/DL6Pvn5iB/nN4OTaKs6D5vwBS8+7snX0w7rmp939hfwTQ==",
        "id": 5
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2230264149.176499,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_F",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "xMEtnHwdWz8bdCnaPvSDIKUpkWVs9U1e",
        "id": 6
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2233317759.222764,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_R_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"07xoma6rww1kVzuIRtFVUAuF1jD+yqXy/rNtFg4x0RFHYYf+BMZnNCZLljqkBabscXrNshHkG++iB7gqNYUzX1ASzQiDSF7BrKhsH5LxLok=\"",
        "id": 7
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2233317759.222871,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_R_T_IV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"OrsPsdB2Mdjao4Pna0pwLA==\"",
        "id": 8
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1602684159.22293,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SPC_SI",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "mall.xLNNNtUTeiLg30Tn0bbfBeO3FMTbVHq1",
        "id": 9
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2233317752.884506,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_U",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "69252628",
        "id": 10
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "csrftoken",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "ldb6jtMOuafKd3Z4H8MMN7NGQQ0K9Dwd",
        "id": 11
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 2230264149,
        "hostOnly": true,
        "httpOnly": true,
        "name": "REC_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "03d61f6e-f197-11ea-8772-f898ef6c83f7",
        "id": 12
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_IA",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "1",
        "id": 13
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 2233317759.222901,
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"07xoma6rww1kVzuIRtFVUAuF1jD+yqXy/rNtFg4x0RFHYYf+BMZnNCZLljqkBabscXrNshHkG++iB7gqNYUzX1ASzQiDSF7BrKhsH5LxLok=\"",
        "id": 14
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 2233317759.222837,
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_T_IV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"OrsPsdB2Mdjao4Pna0pwLA==\"",
        "id": 15
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "welcomePkgShown",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "true",
        "id": 16
    }
];

module.exports = {
    cookies,
    coinUrl,
    luckyUrl
}