const homeUrl = 'https://shopee.vn/';
const coinUrl = 'https://shopee.vn/shopee-coins';
const luckyUrl = 'https://shopee.vn/quatangshopee';
const cookies = [
    {
        "domain": ".shopee.vn",
        "expirationDate": 253402257600,
        "hostOnly": false,
        "httpOnly": false,
        "name": "G_ENABLED_IDPS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "google",
        "id": 1
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1600652019.647076,
        "hostOnly": false,
        "httpOnly": false,
        "name": "REC_MD_41_1000121",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1600652019_0_50_0_45",
        "id": 2
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2230264165.861061,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_CLIENTID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "xMEtnHwdWz8bdCnaupqmddqmoxadfhfk",
        "id": 3
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2231371869.611289,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_EC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "Ro5Uu5cCv8qexx4atXoxa3aQYk2UHw+IETlhFPrsP+i6kqIc7tNfegId3nxNbRVsTLCxhJRHY5GGNkBNdJiUqqPnsU8Ck/yYk2qO2aFp4Kk9exCqGcevCvo47OAeXohXK5jEW5lSFFnRjNx4AMEpoOO+mDIAiJWjZ2860wwnxL0=",
        "id": 4
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2230264149.176499,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_F",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "xMEtnHwdWz8bdCnaPvSDIKUpkWVs9U1e",
        "id": 5
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2231371870.512197,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_R_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"EHEidfZwhTdKEPU/DatRM7kuKkgpySY26snQIk+UOsfzxVIvPIYMT74Z6R852y4exz6fco/gExHXsLWkQCQ/I+AeDFGx0GLr+CywijFgxhI=\"",
        "id": 6
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2231371870.51278,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_R_T_IV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"B5f7aWZ/kyvsjz8hvLd4oQ==\"",
        "id": 7
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 1600738270.513196,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SPC_SI",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "mall.bute4QBoBPOAZFsfdhBVpfWruJs5JHBB",
        "id": 8
    },
    {
        "domain": ".shopee.vn",
        "expirationDate": 2231371715.615937,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SPC_U",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "69252628",
        "id": 9
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "csrftoken",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "zt2KEolcWXhqQdJ3Ve33MhnrKMdY6MMG",
        "id": 10
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 2230264149.17652,
        "hostOnly": true,
        "httpOnly": true,
        "name": "REC_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "03d61f6e-f197-11ea-8772-f898ef6c83f7",
        "id": 11
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_IA",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "1",
        "id": 12
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 2231371870.512894,
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_T_ID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"EHEidfZwhTdKEPU/DatRM7kuKkgpySY26snQIk+UOsfzxVIvPIYMT74Z6R852y4exz6fco/gExHXsLWkQCQ/I+AeDFGx0GLr+CywijFgxhI=\"",
        "id": 13
    },
    {
        "domain": "shopee.vn",
        "expirationDate": 2231371870.512331,
        "hostOnly": true,
        "httpOnly": false,
        "name": "SPC_T_IV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "\"B5f7aWZ/kyvsjz8hvLd4oQ==\"",
        "id": 14
    },
    {
        "domain": "shopee.vn",
        "hostOnly": true,
        "httpOnly": false,
        "name": "welcomePkgShown",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "true",
        "id": 15
    }
];

module.exports = {
    cookies,
    homeUrl,
    coinUrl,
    luckyUrl
}